app/partner/urls.py
from django.conf.urls import patterns, url, include
from arcticles.models import Article
#from views import ArticleDetail
from django.views.generic import DetailView
from partner.views import *
from django.contrib.auth import views as auth_views, logout
from accounts.forms import MyPasswordResetForm
from registration.backends.default.views import ActivationView

urlpatterns = patterns('',
    url(r'^$', HomePartnerView.as_view(), name='partner-home'),

    url(r'^stat/$', StatView.as_view(), name='partner-stat'),
    url(r'^stat/$', StatView.as_view(), name='cabinet-rules'),


    url(r'^leads/$', LidsListView.as_view(), name='partner-leads'),

    url(r'^links/$', PartnerLinksListView.as_view(), name='partner-links'),

    url(r'^promo/$', PromoPageView.as_view(), name='partner-promo'),

    url(r'^output/$', OutputView.as_view(), name='partner-output'),
    url(r'^output/(?P<id>[-\w]+)/$', bid_delete, name='partner-output-delete'),

    url(r'^info/$', InformationPageView.as_view(), name='partner-info'),

    #url(r'^testik/$', TestikPageView.as_view(), name='testik'),

    url(r'^settings/$', settingsuser, name='partner-settings'),

    #url(r'^(?P<slug>[-\w]+)/$', ArticleDetail.as_view(), name='common-article'),
    url(r'^login/$', login, {}, name='auth_login_partner'),
    url(r'^login/$', login, {}, name='auth_login'),
    url(r'^logout/$', logout_view, name='partner_logout'),


    url(r'^register/$', registration,
            name='registration_partner'),
    url(r'^register/$', registration,
            name='registration'),

    url(r'^password/change/$', auth_views.password_change,
            name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
            name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset,
            {'password_reset_form': MyPasswordResetForm}, name='password_reset'),
    url(r'^password/reset/done/$',
            auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/complete/$',
            auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.password_reset_confirm, name='password_reset_confirm'),

    #url(r'^activate/(?P<activation_key>\w+)/$',
    #                       ActivationView.as_view(),
    #                       name='registration_activate_partner'),

    url(r'^stat/$', StatView.as_view(), name='cabinet-view'),

    (r'^accounts/', include('registration.backends.default.urls')),

    #partner admin
    url(r'^admin/', include('padmin.urls')),
    )

propforex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts.forms import MyPasswordResetForm
from admin.views import UsersAdminView
import core
from core.views import HomePageView, CabinetRulesView, BuyTicketView, ActiveTicketView, InActiveTicketView, AffilateView, \
    CabinetView, MaterialView, HomePageEnView
from django.contrib.staticfiles import views
from django.contrib.auth import views as auth_views, logout
from accounts.views import (login)

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^yandex_67fb7d7c49fd886a.txt', core.views.sert, name='sert'), 
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^en$', HomePageEnView.as_view(), name='home-en'),
    url(r'^cabinet/rules$', CabinetRulesView.as_view(), name='cabinet-rules'),
    url(r'^cabinet/buy-ticket/', BuyTicketView.as_view(), name='buy-ticket'),
    url(r'^cabinet/tickets/', ActiveTicketView.as_view(), name='tickets'),
    url(r'^cabinet/intickets/', InActiveTicketView.as_view(), name='intickets'),
    url(r'^cabinet/affilate/(?P<id>[-\w]+)/$', core.views.bid_delete, name='affilate-delete'),
    url(r'^cabinet/affilate/', AffilateView.as_view(), name='affilate'),
    url(r'^cabinet/material/', MaterialView.as_view(), name='material'),
    url(r'^cabinet/user/(?P<email>\w+)/',core.views.cancel_send,name="cabinet-cancel-send"),
    url(r'^cabinet/user/', core.views.edituser, name='user-edit'),

    url(r'^cabinet/', CabinetView.as_view(), name='cabinet-view'),
    url(r'^order/', core.views.order_call, name='order-call'),

    url(r'^next/', core.views.next, name='next_registration'),


    url(r'^login/$', login, {}, name='auth_login'),
    url(r'^accounts/logout/$', core.views.logout_view, name='auth_logout'),

    url(r'^accounts/register/$', 'accounts.views.registration',
            name='registration'),
    url(r'^accounts/password/change/$', auth_views.password_change,
            name='password_change'),
    url(r'^accounts/password/change/done/$', auth_views.password_change_done,
            name='password_change_done'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
            {'password_reset_form': MyPasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$',
            auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
            auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.password_reset_confirm, name='password_reset_confirm'),

    (r'^accounts/', include('registration.backends.default.urls')),

    #add new user landing N1
    url(r'^new-user/lp/', core.views.new_landing_user, name='new_landing_user'),

    #urls robokassa
    url(r'^robokassa/', include('robokassa.urls')),
    url(r'^oplata/', include('robokassa.urls')),
    url(r'^oplata/(?P<ticket_id>[-\w]+)/$', core.views.pay_with_robokassa, name='cabinet-oplata'),

    #partner
    #url(r'^partner/', include('partner.urls')),

    #admin
    url(r'^manager/', include('admin.urls')),
    #url(r'^manager/', UsersAdminView.as_view(), name='admin-users'),

    url(r'^admin/', include(admin.site.urls)),

    url('', include('arcticles.urls')),
)

urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
]

app/core/models.py
# -*- coding: utf-8 -*-
import datetime
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db.models.signals import post_save
from django.template.loader import render_to_string
from django.utils import timezone
from django.db import models

# Create your models here.
import requests
from accounts import UserProfile
from accounts.models import Notification
from webaccounts.models import ReferalHistory, UserProfile as WB


def next_weekday(d, weekday):
    days_ahead = weekday - d.weekday()
    if days_ahead <= 0: # Target day already happened this week
        days_ahead += 7
    return d + datetime.timedelta(days_ahead)

class Ticket(models.Model):
    value = models.PositiveIntegerField(default=0, verbose_name=u'Стоимость билета')
    duration = models.PositiveIntegerField(default=14, verbose_name=u'Длительность отбора')
    goal = models.PositiveIntegerField(default=100, verbose_name=u'Цель по прибыли')
    sag_max = models.IntegerField(default=20, verbose_name=u'Макс.дневная просадка')
    sag_min = models.IntegerField(default=50, verbose_name=u'Максимальная просадка')
    amount = models.PositiveIntegerField(default=1000, verbose_name=u'Сумма в управление')
    publish = models.BooleanField(verbose_name="Опубликовано", default=True)

    def __unicode__(self):
            return self.value

class YesTicket(models.Model):
    TYPE_ONE = 0
    TYPE_TWO = 1

    TYPE_SYSTEM = (
        (TYPE_ONE, u'Активный'),
        (TYPE_TWO, u'Неактивен'),
    )
    STATUS_ONE = 1
    STATUS_TWO = 2
    STATUS_THREE = 3
    STATUS_FOUR = 4
    STATUS_FIVE = 5
    STATUS_SIX = 6
    STATUS_SEVEN = 7

    TYPE_STATUS = (
        (STATUS_ONE, u'Превышено дневное ограничение по просадке'),
        (STATUS_TWO, u'Превышена максимально допустимая просадка'),
        (STATUS_THREE, u'Цель по прибыли не выполнена'),
        (STATUS_FOUR, u'Количество прибыльных дней не соответствует условиям'),
        (STATUS_FIVE, u'Использованы запрещённые торговые системы'),
        (STATUS_SIX, u'Установлено дополнительное испытание'),
		(STATUS_SEVEN, u'Бесплатный билет/"Второй шанс"'),
    )
    UPR_ONE = 0
    UPR_TWO = 1

    TYPE_UPR = (
        (UPR_ONE, u'Первый вариант'),
        (UPR_TWO, u'Второй')
    )
    time_start = models.DateTimeField(default=timezone.now, blank=True, null=True, verbose_name=u'Дата старта')
    user = models.ForeignKey(UserProfile, related_name='user_ticket', verbose_name=u'Пользователь')
    ticket = models.ForeignKey(Ticket, related_name='yes_ticket', verbose_name=u'Билет')
    invoice = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Счет брокера')
    password = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Пароль')
    server = models.CharField(max_length=50, default='ConcordBay-DemoUK', blank=True, null=True, verbose_name=u'Сервер')
    active = models.IntegerField(choices=TYPE_SYSTEM, blank=True, null=True, default=0, verbose_name=u'Активность')
    status = models.IntegerField(choices=TYPE_STATUS, blank=True, null=True, verbose_name=u'Статус билета')

    order = models.IntegerField(default=0,blank=True,null=True)
    send = models.BooleanField(default=False)
    upr_status = models.BooleanField(default=False, verbose_name=u'Управляющий билет')

    commentary = models.TextField(max_length=1200, blank=True, null=True, verbose_name=u'Комментарий')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def com(self):
        if len(self.commentary) >= 30:
            return self.commentary[:30] + '...'
        else:
            return self.commentary[:30]

    def time_finish(self):
        return self.time_start + datetime.timedelta(weeks=2)

    def all_amounts(self):
        return self.ticket.value

    def save(self, *args, **kwargs):
        dt = datetime.datetime.now()
        if getattr(self, 'time_start', True):
            pass
        else:
            self.time_start = next_weekday(dt, 0)
        super(YesTicket, self).save()


class OrderCall(models.Model):
    TYPE_WHO = 1
    TYPE_REP = 2
    TYPE_LIST = 3

    TYPE_CHOICES = (
        (TYPE_WHO, 'Ожидает'),
        (TYPE_REP, 'Не дозвонились'),
        (TYPE_LIST, 'Завершен'),
    )
    result = models.IntegerField(choices=TYPE_CHOICES, blank=True, null=True, default=1, verbose_name=u'Статус')
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Имя')
    phone = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Телефон')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Order(models.Model):
    user = models.ForeignKey(UserProfile, related_name='order_user', verbose_name=u'юзер')
    ticket = models.ForeignKey(Ticket, related_name='order_ticket', verbose_name=u'Билет')
    amount = models.PositiveIntegerField(verbose_name=u'Сумма в оплаты в рублях')
    check = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.check:
            yes = YesTicket()
            yes.order = self.id
            yes.user = self.user
            yes.ticket = self.ticket
            yes.save()
        super(Order, self).save()


#Отправка оповещение после добавления билета
def update_stock(sender, instance, **kwargs):
    if kwargs["created"]:
        noti = Notification.objects.get(id=1)
        if noti.pochta:
           users = UserProfile.objects.get(id=instance.user.id)
           try:
               ref =  ReferalHistory.objects.get(refer=users)
               con = WB.objects.get(id=ref.ref.user_id)
               if ref.result != 2:
                   ref.result = 2
                   ref.price_lid = con.cont_lid
                   ref.save()
           except:
                pass
           text_content = 'Куплен новый билет'
           html_content = render_to_string('mailchimp/ticket.html', {'users': users})
           msg = EmailMultiAlternatives('Куплен новый билет', text_content, settings.EMAIL_HOST_USER,  [noti.email])
           msg.attach_alternative(html_content, "text/html")
           msg.send()

# register the signal
post_save.connect(update_stock, sender=YesTicket, dispatch_uid="update_stock_count")

#Отправка оповещение после добавления обратного звонка
def call_stock(sender, instance, **kwargs):
    if kwargs["created"]:
        noti = Notification.objects.get(id=1)
        if noti.pochta:
           users = UserProfile.objects.get(username='admin')
           text_content = 'Пользователь заказал обратный звонок'
           html_content = render_to_string('mailchimp/call.html', {'users': users})
           msg = EmailMultiAlternatives('Пользователь заказал обратный звонок', text_content, settings.EMAIL_HOST_USER,  [noti.email])
           msg.attach_alternative(html_content, "text/html")
           msg.send()

# register the signal
post_save.connect(call_stock, sender=OrderCall, dispatch_uid="call_stock_count")


#add date
def update_stocks(sender, instance, **kwargs):
    if kwargs["created"]:
        dt = datetime.datetime.now()
        yes = YesTicket.objects.get(id=instance.id)
        yes.time_start = next_weekday(dt, 0)
        yes.save()


# register the signal
post_save.connect(update_stocks, sender=YesTicket, dispatch_uid="update_stock_count")



#Отправка add_listbuytciket
def add_listbuytciket(sender, instance, **kwargs):
    if kwargs["created"]:
        try:
           userr = UserProfile.objects.get(id=instance.user.id)
           name = ''
           if userr.first_name:
               name = userr.get_full_name()
           payload = {'name': name, 'email': userr.email, 'list': settings.BUYTICKET_LIST}
           r = requests.post("http://mail.propforex.co/subscribe", data=payload)
           print(r)
        except:
            pass

# register the signal
post_save.connect(add_listbuytciket, sender=YesTicket, dispatch_uid="add_listbuytciket")

app/partner/models.py
# -*- coding: utf-8 -*-
import datetime
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db.models.signals import post_save
from django.template.loader import render_to_string
from django.utils import timezone
from django.db import models
from arcticles.models import Article


class Links(models.Model):
    landing = models.ForeignKey(Article, verbose_name=u'Лэндинг', blank=True, null=True)
    user_id = models.IntegerField(default=0, blank=True, null=True)
    name = models.CharField(verbose_name=u'Название', max_length=250)

    glav = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
            return self.name

    #куда ведет
    def partner_link(self):
        if self.glav:
            return settings.OSN_ULR
        else:
            return settings.OSN_ULR + self.landing.slug + '/'

    #Добавленная ссылка
    def partner_link_ref(self):
        if self.glav:
            return settings.OSN_ULR +  '?pl=' + str(self.user_id)+'&l='+str(self.id)
        else:
            return settings.OSN_ULR + self.landing.slug + '/?pl=' + str(self.user_id)+'&l=' +str(self.id)

#Лиды
"""
class Lids(models.Model):
    user_id = models.IntegerField(default=0, blank=True, null=True)
    channel = models.ForeignKey(Links, verbose_name=u'юзера канал')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
            return self.channel.name
"""

templates/partner/partner-lids-list.html
{% extends 'partner/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load url from future %}
{% load partner_extras %}

{% block title %}PropForex - Лиды{% endblock %}

{% block content_header %}
<h1 class="page-header">Лиды</h1>
{% endblock %}

{% block content %}

<div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>ID</th>
                                        <th>Дата регистрации</th>
                                        <th>Канал</th>
                                        <th>Статус</th>
                                        <th>Дата изменения Статуса</th>
                                        <th>Цена лида</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for buy in object_list %}
									<tr>
                                    <td>{{ forloop.counter }}</td>
									<td>{{ buy.refer.id }}</td>
									<td>{{ buy.created|date:"j/n/Y H:i:s" }}</td>
                                    <td>{{ buy.landing.name }}</td>
                                    <td>{{ buy.get_result_display }}</td>
                                    <td>
                                        {% if buy.result == 2 or buy.result == 3 %}
                                         {{ buy.updated|date:"j/n/Y H:i:s" }}
                                        {% endif %}
                                    </td>
                                    <td>{{ buy.ref.user_id|price_lid }}</td>
									</tr>
								{% endfor %}
                                </tbody>
                            </table>
</div>
{% endblock %}

templates/partner/partner-output.html
{% extends 'partner/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load url from future %}

{% block title %}PropForex - Вывод средств{% endblock %}

{% block content_header %}
<h1 class="page-header">Вывод средств</h1>
{% endblock %}

{% block content %}

{% if success %}
<div class="alert alert-warning">{{ success }}</div>
{% endif %}

{% if errorss %}
<div class="alert alert-warning">{{ errorss }}</div>
{% endif %}
{% if users.number_sistem  or success %}
{% else %}
<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Добавление системы вывода денежных средств (Можно добавить только один раз)</h3>
				</div>
                <div class="panel-body">
				<form class="form-signin col-lg-4" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ next }}">
                <div class="form-group">
                    <h4>Выберете платежную систему</h4>
                    <select class="form-control" name="sistema">
                        <option value="0">QIWI</option>
                        <option value="1">Яндекс.Деньги</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="number" placeholder="Введите номер" class="form-control" name="number" id="id_summa">
                </div>

                <div class="form-group">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Добавить</button>
                </div>
                </form>
                </div>
</div><br>
{% endif %}

{% if yesout == True %}
<div class="alert alert-warning">Заявка на вывод успешно создана</div>
{% elif yesout == False %}
<div class="alert alert-warning">Ошибка! проверьте ваши данные</div>
{% endif %}
{% if errors %}
<div class="alert alert-warning">{{ errors }}</div>
{% endif %}
<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Вывод средств</h3>
				</div>
                <div class="panel-body">
				<form class="form-signin col-lg-4" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ next }}">
                <div class="form-group">
                    <input type="text" placeholder="Введите желаемую сумму на вывод" class="form-control" name="summa" id="id_summa">
                </div>

                <div class="form-group">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
                </div>
                </form>
                </div>

<!--br>
 {% if historys %}
<h3 class="panel-title">История заявок на вывод средств</h3>
<br-->
<table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Дата</th>
                                        <th>Сумма</th>
                                        <th>Система</th>
                                        <th>Кошелек</th>
                                        <th>Статус</th>

                                    </tr>
                                </thead>
                                <tbody>
                                {% for history in historys %}
                                <tr>
		                                	<td>{{ history.created|date:"j.n.Y" }}</td>
	                                		<td>{{ history.sum }}</td>
	                                		<td>{{ history.user.get_sistemas_display }}</td>
                                            <td>{{ history.user.number_sistem }}</td>

		                                	<td>

                                                {{ history.get_result_display }}
                                                {% if history.result == 0 %}(<a href="{% url 'partner-output-delete' history.id %}">Отменить</a>){% endif %}
                                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
</table>
</div>
{% endif %}
{% endblock %}

templates/partner/partner-stat.html
{% extends 'partner/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load url from future %}
{% load partner_extras %}

{% block title %}PropForex - Статистика{% endblock %}

{% block content_header %}
<h1 class="page-header">Статистика</h1>
{% endblock %}

{% block content %}
<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Выберите период</h3>
			</div>
			<div class="panel-body">
            <div class="week-search" style="margin-left: 20px;">
					<a class="btn btn-default {% if request.get_full_path == '/stat/' %}active{% endif %}" role="button" href="{% url 'partner-stat' %}">Неделя</a>
					<a class="btn btn-default {% if request.get_full_path == '/stat/?day=-30' %}active{% endif %}" role="button" href="/stat/?day=-30">Месяц</a>
			</div>
            <form action="{{ request.get_full_path }}" method="get">
            <div class="time-search">
                <input type="hidden" value="{{ time_start }}" id="time_start-val">
                <input type="hidden" value="{{ time_finish }}" id="time_finish-val">
                <input type="hidden" value="{{ channel.id }}" id="id_channel">
				
				<input style="width: 150px;margin-left: 10px;" class="datetimeinput form-control" id="id_time_start" name="time_start" type="text">
				<input style="width: 150px;margin-left: 10px;" class="datetimeinputtwo form-control" id="id_time_finish" name="time_finish" type="text">
				<input style="width: 150px;margin-left: 10px;" class="btn btn-success btn-block" type="submit" value="Отфильтровать">
            {% if time_start_error %}<p>{{ time_start_error }}</p>{% endif %}
            {% if time_finish_error %}<p>{{ time_finish_error }}</p>{% endif %}
            </div>

            <div class="channel-search">

                <select name="channel" style="width:300px" class="js-example-placeholder-single js-states form-control" onchange="this.form.submit()" tabindex="-1">
                {% if channel %}
                    <option value="{{ channel.id }}">{{ channel.name }}</option>
                {% else %}
                    <option></option>
                {% endif %}
                    {% for link in links %}
                        {% if channel.id == link.id %}
                        {% else %}
                    <option value="{{ link.id }}">{{ link.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div></form>
            </div>


							<table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Дата</th>
                                        <th>Переходы</th>
                                        <th>Лиды</th>
                                        <th style="color:blue;">Ожидает</th>
										<th style="color:green;">Принят</th>
										<th style="color:red;">Отклонен</th>
                                        <th>Сумма</th>
										<th>EPC</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for did in date_dats %}
									<tr>
												<td>{{ did|date:"j.n.Y" }}</td>
												<td>{{ ref_list|visit:did }}</td>
												<td>{{ ref_list|leads:did }}</td>
												<td>{{ ref_list|waits:did }}</td>
												<td>{{ ref_list|received:did }}</td>
												<td>{{ ref_list|output:did }}</td>
												<td>{{ ref_list|partner:did }}</td>
												<td>{{ ref_list|epc:did }}</td>
									</tr>
                                {% endfor %}
                                {% if week %}
                                <tr>
		                                	<td>Итого</td>
	                                		<td>{{ visit }}</td>
	                                		<td>{{ leads }}</td>
		                                	<td>{{ waits }}</td>
		                                	<td>{{ received }}</td>
		                                	<td>{{ output }}</td>
                                            <td>{{ partnerka }}</td>
		                                	<td>{{ epc }}</td>
                                </tr>
                                {% endif %}
                                </tbody>
							</table>
</div>
{% endblock %}

templates/partner/partner-user.html
{% extends 'partner/base.html' %}
{% load static from staticfiles %}

{% block title %}Редактировать данные{% endblock %}

{% block content_header %}
<h1 class="page-header">Редактировать данные</h1>
{% endblock %}

 {% block content %}


{% if yesout == True %}
<div class="alert alert-warning">Данные успешно изменены!</div>
{% elif yesout == False %}
<div class="alert alert-warning">Ошибка! проверьте вводимые данные</div>
{% endif %}

<form action="" method="post">{% csrf_token %}
<table cellpadding="5">
  <colgroup><col width="30%">
  <col width="70%">
	</colgroup><tbody><tr>


  <tr>
    <td>Имя:</td>
    <td>
	<div class="form-group">
	<input type="text" name="first_name" value="{{ users.first_name }}" class="form-control">
	</div>
	</td>
  </tr>
  	<tr><td>Телефон:</td>
  	<td>
	<div class="form-group">
	<input type="text" name="phone" value="{{ users.phone }}" class="form-control">
	</div>
	</td>
  </tr>

  <tr>
  	<td></td>
  	<td><input type="submit" value="Сохранить" class="btn btn-lg btn-primary btn-block  pull-right"></td>
  </tr>
</tbody></table>

</form>

{% endblock %}

templates/partner/testik.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form class="form-signin col-lg-4" action="http://mail.propforex.co/subscribe" method="post">
    <input type="text" name="name" value="test">
    <input type="text" name="email" value="test@test.com">
    <input type="text" name="list" value="h892xsDGr8WO2d7uJ00nB0KQ">
    <input  class="btn btn-lg btn-primary btn-block" type="submit" value="Обновить" />
</form>
</body>
</html>