app/admin/urls.py
from django.conf.urls import patterns, url
import admin
from admin.views import login, UsersAdminEditView, ReferalOutView, ReferalOutEditView, notification, TicketAddView, \
    NotificationEditView, TicketDeleteView, UsersAdminDeleteView, OrderCallListView, PageListView, PageListEditView, PageListEditAddView
from django.core.urlresolvers import reverse, reverse_lazy
from admin.views import UsersAdminView, TicketListView, DetailTicketView, SettingsTicketView, SettingsTicketEditView, \
    SettingsTicketAddView, SettingsTicketDeleteView, CurencyEditView, OrderCallEditView


urlpatterns = patterns('',
    url(r'^users/delete/(?P<pk>[-\w]+)/$', UsersAdminDeleteView.as_view(success_url=reverse_lazy('admin-users')), name='admin-users-delete'),
    url(r'^users/(?P<pk>[-\w]+)/$', UsersAdminEditView.as_view(success_url=reverse_lazy('admin-users')), name='admin-users-edit'),
    url(r'^users', UsersAdminView.as_view(), name='admin-users'),
    url(r'^send/user/$', admin.views.send_user, name='send-user'),

    url(r'^tickets/settings/add', SettingsTicketAddView.as_view(), name='admin-tickets-settings-add'),
    url(r'^tickets/settings/delete/(?P<pk>[-\w]+)/$', SettingsTicketDeleteView.as_view(), name='admin-tickets-settings-delete'),
    url(r'^tickets/settings/(?P<pk>[-\w]+)/$', SettingsTicketEditView.as_view(success_url=reverse_lazy('admin-tickets-settings')), name='admin-tickets-settings-edit'),
    url(r'^tickets/settings', SettingsTicketView.as_view(), name='admin-tickets-settings'),
    url(r'^tickets/delete/(?P<pk>[-\w]+)/$', TicketDeleteView.as_view(), name='admin-tickets-delete'),
    url(r'^tickets/add', TicketAddView.as_view(), name='admin-tickets-add'),
    url(r'^tickets', TicketListView.as_view(), name='admin-tickets'),
    url(r'^ticket/(?P<pk>[-\w]+)/$', DetailTicketView.as_view(success_url=reverse_lazy('admin-tickets')), name='admin-tickets-edit'),

    url(r'^currency/', CurencyEditView.as_view(), name='currency'),
    url(r'^bids/(?P<pk>[-\w]+)/$', OrderCallEditView.as_view(), name='order-admin-edit'),
    url(r'^bids/', OrderCallListView.as_view(), name='admin-bids'),
    url(r'^notification/', NotificationEditView.as_view(), name='admin-notification'),
    url(r'^affilate/(?P<pk>[-\w]+)/$', ReferalOutEditView.as_view(), name='affilate-admin-edit'),
    url(r'^affilate/', ReferalOutView.as_view(), name='affilate-admin'),
    url(r'^api/notification/', notification, name='notification-api'),

    url(r'^pages/add', PageListEditAddView.as_view(), name='admin-pages-add'),
    url(r'^pages/(?P<pk>[-\w]+)/$', PageListEditView.as_view(), name='admin-pages-edit'),
    url(r'^pages', PageListView.as_view(), name='admin-pages'),

    url(r'^login/$', login, {}, name='auth_login_manager'),

)

propforex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts.forms import MyPasswordResetForm
from admin.views import UsersAdminView
import core
from core.views import HomePageView, CabinetRulesView, BuyTicketView, ActiveTicketView, InActiveTicketView, AffilateView, \
    CabinetView, MaterialView, HomePageEnView
from django.contrib.staticfiles import views
from django.contrib.auth import views as auth_views, logout
from accounts.views import (login)

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^yandex_67fb7d7c49fd886a.txt', core.views.sert, name='sert'), 
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^en$', HomePageEnView.as_view(), name='home-en'),
    url(r'^cabinet/rules$', CabinetRulesView.as_view(), name='cabinet-rules'),
    url(r'^cabinet/buy-ticket/', BuyTicketView.as_view(), name='buy-ticket'),
    url(r'^cabinet/tickets/', ActiveTicketView.as_view(), name='tickets'),
    url(r'^cabinet/intickets/', InActiveTicketView.as_view(), name='intickets'),
    url(r'^cabinet/affilate/(?P<id>[-\w]+)/$', core.views.bid_delete, name='affilate-delete'),
    url(r'^cabinet/affilate/', AffilateView.as_view(), name='affilate'),
    url(r'^cabinet/material/', MaterialView.as_view(), name='material'),
    url(r'^cabinet/user/(?P<email>\w+)/',core.views.cancel_send,name="cabinet-cancel-send"),
    url(r'^cabinet/user/', core.views.edituser, name='user-edit'),

    url(r'^cabinet/', CabinetView.as_view(), name='cabinet-view'),
    url(r'^order/', core.views.order_call, name='order-call'),

    url(r'^next/', core.views.next, name='next_registration'),


    url(r'^login/$', login, {}, name='auth_login'),
    url(r'^accounts/logout/$', core.views.logout_view, name='auth_logout'),

    url(r'^accounts/register/$', 'accounts.views.registration',
            name='registration'),
    url(r'^accounts/password/change/$', auth_views.password_change,
            name='password_change'),
    url(r'^accounts/password/change/done/$', auth_views.password_change_done,
            name='password_change_done'),
    url(r'^accounts/password/reset/$', auth_views.password_reset,
            {'password_reset_form': MyPasswordResetForm}, name='password_reset'),
    url(r'^accounts/password/reset/done/$',
            auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
            auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.password_reset_confirm, name='password_reset_confirm'),

    (r'^accounts/', include('registration.backends.default.urls')),

    #add new user landing N1
    url(r'^new-user/lp/', core.views.new_landing_user, name='new_landing_user'),

    #urls robokassa
    url(r'^robokassa/', include('robokassa.urls')),
    url(r'^oplata/', include('robokassa.urls')),
    url(r'^oplata/(?P<ticket_id>[-\w]+)/$', core.views.pay_with_robokassa, name='cabinet-oplata'),

    #partner
    #url(r'^partner/', include('partner.urls')),

    #admin
    url(r'^manager/', include('admin.urls')),
    #url(r'^manager/', UsersAdminView.as_view(), name='admin-users'),

    url(r'^admin/', include(admin.site.urls)),

    url('', include('arcticles.urls')),
)

urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
]

app/core/models.py
# -*- coding: utf-8 -*-
import datetime
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db.models.signals import post_save
from django.template.loader import render_to_string
from django.utils import timezone
from django.db import models

# Create your models here.
import requests
from accounts import UserProfile
from accounts.models import Notification
from webaccounts.models import ReferalHistory, UserProfile as WB


def next_weekday(d, weekday):
    days_ahead = weekday - d.weekday()
    if days_ahead <= 0: # Target day already happened this week
        days_ahead += 7
    return d + datetime.timedelta(days_ahead)

class Ticket(models.Model):
    value = models.PositiveIntegerField(default=0, verbose_name=u'Стоимость билета')
    duration = models.PositiveIntegerField(default=14, verbose_name=u'Длительность отбора')
    goal = models.PositiveIntegerField(default=100, verbose_name=u'Цель по прибыли')
    sag_max = models.IntegerField(default=20, verbose_name=u'Макс.дневная просадка')
    sag_min = models.IntegerField(default=50, verbose_name=u'Максимальная просадка')
    amount = models.PositiveIntegerField(default=1000, verbose_name=u'Сумма в управление')
    publish = models.BooleanField(verbose_name="Опубликовано", default=True)

    def __unicode__(self):
            return self.value

class YesTicket(models.Model):
    TYPE_ONE = 0
    TYPE_TWO = 1

    TYPE_SYSTEM = (
        (TYPE_ONE, u'Активный'),
        (TYPE_TWO, u'Неактивен'),
    )
    STATUS_ONE = 1
    STATUS_TWO = 2
    STATUS_THREE = 3
    STATUS_FOUR = 4
    STATUS_FIVE = 5
    STATUS_SIX = 6
    STATUS_SEVEN = 7

    TYPE_STATUS = (
        (STATUS_ONE, u'Превышено дневное ограничение по просадке'),
        (STATUS_TWO, u'Превышена максимально допустимая просадка'),
        (STATUS_THREE, u'Цель по прибыли не выполнена'),
        (STATUS_FOUR, u'Количество прибыльных дней не соответствует условиям'),
        (STATUS_FIVE, u'Использованы запрещённые торговые системы'),
        (STATUS_SIX, u'Установлено дополнительное испытание'),
		(STATUS_SEVEN, u'Бесплатный билет/"Второй шанс"'),
    )
    UPR_ONE = 0
    UPR_TWO = 1

    TYPE_UPR = (
        (UPR_ONE, u'Первый вариант'),
        (UPR_TWO, u'Второй')
    )
    time_start = models.DateTimeField(default=timezone.now, blank=True, null=True, verbose_name=u'Дата старта')
    user = models.ForeignKey(UserProfile, related_name='user_ticket', verbose_name=u'Пользователь')
    ticket = models.ForeignKey(Ticket, related_name='yes_ticket', verbose_name=u'Билет')
    invoice = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Счет брокера')
    password = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Пароль')
    server = models.CharField(max_length=50, default='ConcordBay-DemoUK', blank=True, null=True, verbose_name=u'Сервер')
    active = models.IntegerField(choices=TYPE_SYSTEM, blank=True, null=True, default=0, verbose_name=u'Активность')
    status = models.IntegerField(choices=TYPE_STATUS, blank=True, null=True, verbose_name=u'Статус билета')

    order = models.IntegerField(default=0,blank=True,null=True)
    send = models.BooleanField(default=False)
    upr_status = models.BooleanField(default=False, verbose_name=u'Управляющий билет')

    commentary = models.TextField(max_length=1200, blank=True, null=True, verbose_name=u'Комментарий')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def com(self):
        if len(self.commentary) >= 30:
            return self.commentary[:30] + '...'
        else:
            return self.commentary[:30]

    def time_finish(self):
        return self.time_start + datetime.timedelta(weeks=2)

    def all_amounts(self):
        return self.ticket.value

    def save(self, *args, **kwargs):
        dt = datetime.datetime.now()
        if getattr(self, 'time_start', True):
            pass
        else:
            self.time_start = next_weekday(dt, 0)
        super(YesTicket, self).save()


class OrderCall(models.Model):
    TYPE_WHO = 1
    TYPE_REP = 2
    TYPE_LIST = 3

    TYPE_CHOICES = (
        (TYPE_WHO, 'Ожидает'),
        (TYPE_REP, 'Не дозвонились'),
        (TYPE_LIST, 'Завершен'),
    )
    result = models.IntegerField(choices=TYPE_CHOICES, blank=True, null=True, default=1, verbose_name=u'Статус')
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Имя')
    phone = models.CharField(max_length=50, blank=True, null=True, verbose_name=u'Телефон')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Order(models.Model):
    user = models.ForeignKey(UserProfile, related_name='order_user', verbose_name=u'юзер')
    ticket = models.ForeignKey(Ticket, related_name='order_ticket', verbose_name=u'Билет')
    amount = models.PositiveIntegerField(verbose_name=u'Сумма в оплаты в рублях')
    check = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.check:
            yes = YesTicket()
            yes.order = self.id
            yes.user = self.user
            yes.ticket = self.ticket
            yes.save()
        super(Order, self).save()


#Отправка оповещение после добавления билета
def update_stock(sender, instance, **kwargs):
    if kwargs["created"]:
        noti = Notification.objects.get(id=1)
        if noti.pochta:
           users = UserProfile.objects.get(id=instance.user.id)
           try:
               ref =  ReferalHistory.objects.get(refer=users)
               con = WB.objects.get(id=ref.ref.user_id)
               if ref.result != 2:
                   ref.result = 2
                   ref.price_lid = con.cont_lid
                   ref.save()
           except:
                pass
           text_content = 'Куплен новый билет'
           html_content = render_to_string('mailchimp/ticket.html', {'users': users})
           msg = EmailMultiAlternatives('Куплен новый билет', text_content, settings.EMAIL_HOST_USER,  [noti.email])
           msg.attach_alternative(html_content, "text/html")
           msg.send()

# register the signal
post_save.connect(update_stock, sender=YesTicket, dispatch_uid="update_stock_count")

#Отправка оповещение после добавления обратного звонка
def call_stock(sender, instance, **kwargs):
    if kwargs["created"]:
        noti = Notification.objects.get(id=1)
        if noti.pochta:
           users = UserProfile.objects.get(username='admin')
           text_content = 'Пользователь заказал обратный звонок'
           html_content = render_to_string('mailchimp/call.html', {'users': users})
           msg = EmailMultiAlternatives('Пользователь заказал обратный звонок', text_content, settings.EMAIL_HOST_USER,  [noti.email])
           msg.attach_alternative(html_content, "text/html")
           msg.send()

# register the signal
post_save.connect(call_stock, sender=OrderCall, dispatch_uid="call_stock_count")


#add date
def update_stocks(sender, instance, **kwargs):
    if kwargs["created"]:
        dt = datetime.datetime.now()
        yes = YesTicket.objects.get(id=instance.id)
        yes.time_start = next_weekday(dt, 0)
        yes.save()


# register the signal
post_save.connect(update_stocks, sender=YesTicket, dispatch_uid="update_stock_count")



#Отправка add_listbuytciket
def add_listbuytciket(sender, instance, **kwargs):
    if kwargs["created"]:
        try:
           userr = UserProfile.objects.get(id=instance.user.id)
           name = ''
           if userr.first_name:
               name = userr.get_full_name()
           payload = {'name': name, 'email': userr.email, 'list': settings.BUYTICKET_LIST}
           r = requests.post("http://mail.propforex.co/subscribe", data=payload)
           print(r)
        except:
            pass

# register the signal
post_save.connect(add_listbuytciket, sender=YesTicket, dispatch_uid="add_listbuytciket")

templates/core/affilate.html
{% extends 'core/cabinet.html' %}
{% load static from staticfiles %}

{% block title %}Партнерская программа{% endblock %}

{% block content_header %}
<h1 class="page-header">Партнерская программа</h1>
<ol class="breadcrumb"><li><i class="fa fa-dashboard"></i>  <a class="B_homeCrumb" href="/" title="Главная">Главная</a></li> / <a class="B_crumb" href="/cabinet/" title="Личный кабинет">Личный кабинет</a> / <li class="active"><i class="fa fa-edit"></i> <span class="B_currentCrumb">Партнёрка</span></li> </ol>
{% endblock %}

 {% block content %}
     <!--
<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Баннеры</h3>
			</div>
			<div class="panel-body">
                Баннеры тут
			</div>
</div>
-->
<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Выберите период</h3>
			</div>
			<div class="panel-body">
					<a class="btn btn-xs btn-default {% if request.get_full_path == '/cabinet/affilate/' %}active{% endif %}" role="button" href="{% url 'affilate' %}">Сегодня</a>
					<a class="btn btn-xs btn-default {% if request.get_full_path == '/cabinet/affilate/?day=-7' %}active{% endif %}" role="button" href="{% url 'affilate' %}?day=-7">Неделя</a>
					<a class="btn btn-xs btn-default {% if request.get_full_path == '/cabinet/affilate/?day=-30' %}active{% endif %}" role="button" href="{% url 'affilate' %}?day=-30">Месяц</a>
					<a class="btn btn-xs btn-default {% if request.get_full_path == '/cabinet/affilate/?day=-365' %}active{% endif %}" role="button" href="{% url 'affilate' %}?day=-365">Год</a>
			</div>


							<table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Дата от</th>
                                        <th>Переходы по ссылке</th>
                                        <th>Регистрации пользовалелей</th>
                                        <th>Количество оплаченых билетов</th>
										<th>Общая сумма продаж $</th>
										<th>Начисленная комиссия (10% с продаж)$</th>
										<th>EPC $</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <tr>
		                                	<td>{{ dates|date:"j.n.Y" }}</td>
	                                		<td>{{ ref_list.count }}</td>
	                                		<td>{{ all_refer }}</td>
		                                	<td>{{ count_buy }}</td>
		                                	<td>${{ summa_buy }}</td>
		                                	<td>${{ amount_buy_two }}</td>
		                                	<td>${{ epct }}</td>
                                </tr>
                                </tbody>
							</table>
</div>
<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Ваша партнёрская ссылка (начисляется 10% с продаж привлеченных клиентов)</h3>
				</div>
				<div class="panel-body"><a class="" target="_blank" href="http://propforex.co/?pl={{ user.id }}">http://propforex.co/?pl={{ user.id }}</a> - На главную страницу PropForex.co</div>
				<!--div class="panel-body">2) <a class="" target="_blank" href="http://propforex.co/lp2/?pl={{ user.id }}">http://propforex.co/lp2/?pl={{ user.id }}</a> - Дополнительный Landing Page</div-->


				<div class="list-group">
					<span class="list-group-item active">Баланс - ${{ balance }}</span>
					<span class="list-group-item">Заработано всего - ${{ epc }} </span>
					<span class="list-group-item">Выведено - ${{ job_out }}</span>
				</div>

</div>

{% if success %}
<div class="alert alert-warning">{{ success }}</div>
{% endif %}

{% if errorss %}
<div class="alert alert-warning">{{ errorss }}</div>
{% endif %}
{% if users.sistemas == 0 or users.sistemas == 1 or success %}
{% else %}
<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Добавление системы вывода денежных средств (Можно добавить только один раз)</h3>
				</div>
                <div class="panel-body">
				<form class="form-signin col-lg-4" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ next }}">
                <div class="form-group">
                    <h4>Выберете платежную систему</h4>
                    <select class="form-control" name="sistema">
                        <option value="0">QIWI</option>
                        <option value="1">Яндекс.Деньги</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="number" placeholder="Введите номер" class="form-control" name="number" id="id_summa">
                </div>

                <div class="form-group">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Добавить</button>
                </div>
                </form>
                </div>
</div><br>
{% endif %}

{% if yesout == True %}
<div class="alert alert-warning">Заявка на вывод успешно создана</div>
{% elif yesout == False %}
<div class="alert alert-warning">Ошибка! проверьте ваши данные</div>
{% endif %}
{% if errors %}
<div class="alert alert-warning">{{ errors }}</div>
{% endif %}
<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Вывод средств</h3>
				</div>
                <div class="panel-body">
				<form class="form-signin col-lg-4" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ next }}">
                <div class="form-group">
                    <input type="text" placeholder="Введите желаемую сумму на вывод (от $10)" class="form-control" name="summa" id="id_summa">
                </div>

                <div class="form-group">
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
                </div>
                </form>
                </div>

<!--br>
 {% if historys %}
<h3 class="panel-title">История заявок на вывод средств</h3>
<br-->
<table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Дата</th>
                                        <th>Сумма</th>
                                        <th>Система</th>
                                        <th>Кошелек</th>
                                        <th>Статус</th>

                                    </tr>
                                </thead>
                                <tbody>
                                {% for history in historys %}
                                <tr>
		                                	<td>{{ history.created|date:"j.n.Y" }}</td>
	                                		<td>${{ history.sum }}</td>
	                                		<td>{{ history.user.get_sistemas_display }}</td>
                                            <td>{{ history.user.number_sistem }}</td>
		                                	<td>
                                                {{ history.get_result_display }}
                                                {% if history.result == 0 %}(<a href="{% url 'affilate-delete' history.id %}">Отменить</a>){% endif %}
                                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
</table>
</div>
{% endif %}
{% endblock %}

templates/core/cabinet-buy-ticket.html
{% extends 'core/cabinet.html' %}
{% load static from staticfiles %}

{% block title %}Купить билет{% endblock %}

{% block content_header %}
<h1 class="page-header">Купить билет</h1>
<ol class="breadcrumb"><li><i class="fa fa-dashboard"></i>  <a class="B_homeCrumb" href="/" title="Главная">Главная</a></li> / <a class="B_crumb" href="/cabinet/" title="Личный кабинет">Личный кабинет</a> / <li class="active"><i class="fa fa-edit"></i> <span class="B_currentCrumb">Купить билет</span></li> </ol>
{% endblock %}

{% block content %}
{% if object_list %}
<!--p>Все значения приведенные в таблице - в USD</p-->
<div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Стоимость билета</th>
                                        <th>Длительность отбора</th>
                                        <th>Цель по прибыли</th>
                                        <th>Макс.дневная просадка</th>
										<th>Максимальная просадка</th>
										<th>Сумма в управление</th>
										<th>Купить</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for buy in object_list %}
									<tr>
									<td>${{ buy.value }}</td>
									<td>{{ buy.duration }} дней</td>
									<td>${{ buy.goal }}</td>
									<td>${{ buy.sag_max }}</td>
									<td>${{ buy.sag_min }}</td>
									<td>${{ buy.amount }}</td>
									<td><a href="{% url 'cabinet-oplata' buy.id %}" class="btn btn-sm btn-success">Купить</a>
									</td>
									</tr>
								{% endfor %}
                                </tbody>
                            </table>
</div>
{% else %}
<div class="alert alert-warning">Нет подходящих записей.</div>
{% endif %}
{% endblock %}

templates/core/cabinet-list-inticket.html
{% extends 'core/cabinet.html' %}
{% load static from staticfiles %}

{% block title %}PropForex - Неактивные билеты{% endblock %}

{% block content_header %}
<h1 class="page-header">Неактивные билеты</h1>
<ol class="breadcrumb"><li><i class="fa fa-dashboard"></i>  <a class="B_homeCrumb" href="/" title="Главная">Главная</a></li> / <a class="B_crumb" href="/cabinet/" title="Личный кабинет">Личный кабинет</a> / <li class="active"><i class="fa fa-edit"></i> <span class="B_currentCrumb">Неактивные билеты</span></li> </ol>
{% endblock %}

{% block content %}
{% if yesticket_list %}
<div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
										<th>Покупка</th>
                                        <th>Начало</th>
                                        <th>Конец</th>
                                        <th>Стартовая</th>
                                        <th>Стоимость</th>
										<th>Статус билета</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for buy in yesticket_list %}
									<tr>
									<td>{{ buy.created|date:"j/n/Y H:i:s" }}</td>
                                    <td>{{ buy.time_start|date:"j/n/Y"  }}</td>
                                    <td>{{ buy.time_finish|date:"j/n/Y"  }}</td>
                                    <td>${{ buy.ticket.amount }}</td>
                                    <td>${{ buy.ticket.value }}</td>
                                    <td>{{ buy.get_status_display }}</td>
									</tr>
								{% endfor %}
                                </tbody>
                            </table>
</div>
{% else %}
<div class="alert alert-warning">Нет подходящих записей.</div>
{% endif %}
{% endblock %}

templates/core/cabinet-list-ticket.html
{% extends 'core/cabinet.html' %}
{% load static from staticfiles %}

{% block title %}PropForex - Активные билеты{% endblock %}

{% block content_header %}
<h1 class="page-header">Активные билеты</h1>
<ol class="breadcrumb"><li><i class="fa fa-dashboard"></i>  <a class="B_homeCrumb" href="/" title="Главная">Главная</a></li> / <a class="B_crumb" href="/cabinet/" title="Личный кабинет">Личный кабинет</a> / <li class="active"><i class="fa fa-edit"></i> <span class="B_currentCrumb">Активные билеты</span></li> </ol>
{% endblock %}

{% block content %}
{% if yesticket_list %}

<div class="alert alert-warning"><span style="color:red;">Внимание!</span> Отмечаем, что начинать торговлю нужно в указанную дату старта в поле "Начало", она устанавливается на ближайший понедельник.<br>Данные "Счет брокера" и "Пароль" будут дополнены администратором в выходные дни биржи, минимум за три часа до её открытия в понедельник.<br>После того, как будет присвоен "Счет брокера" и "Пароль" Вы получите уведомление на почту.</div>

<div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
										<th>Покупка</th>
                                        <th>Начало</th>
                                        <th>Конец</th>
                                        <th>Стартовая</th>
                                        <th>Стоимость</th>
										<th>Счет брокера</th>
										<th>Пароль</th>
										<th>Сервер</th>
                                    </tr>
                                </thead>
								<div class="alert alert-warning"><a href="https://clients.concordbay.ru/ru/p/CD37453B/" target="_blank">Скачать терминал МТ4</a> (откроется в новом окне)</div>
                                <tbody>
                                {% for buy in yesticket_list %}
									<tr {% if buy.upr_status %} style="background-color: #ac2925;color: white;"{% endif %}>
									<td>{{ buy.created|date:"j/n/Y H:i:s" }}</td>
                                    <td>{{ buy.time_start|date:"j/n/Y"  }}</td>
                                    <td>{{ buy.time_finish|date:"j/n/Y"  }}</td>
                                    <td>${{ buy.ticket.amount }}</td>
                                    <td>${{ buy.ticket.value }}</td>
                                    <td>{% if buy.invoice %}{{ buy.invoice }}{% endif %}</td>
                                    <td>{% if buy.password %}{{ buy.password }}{% endif %}</td>
                                    <td>{% if buy.server %}{{ buy.server }}{% endif %}</td>
									</tr>
								{% endfor %}
                                </tbody>
                            </table>
</div>
{% else %}
<div class="alert alert-warning">Нет подходящих записей.</div>
{% endif %}
{% endblock %}